'use client';

import JSZip from 'jszip';
import { toPng } from 'html-to-image';
import type { Project, Screen } from '@/lib/types';

/**
 * The live prototype viewer renders screens with sandbox="allow-scripts"
 * (no allow-same-origin) so hotspot clicks work but the iframe can never
 * reach the parent DOM — good for safety, but it also means the parent
 * can't read that iframe's content back out for a snapshot. For export
 * only, we render into a *different*, temporary hidden iframe with
 * sandbox="allow-same-origin" and no allow-scripts: the opposite tradeoff.
 * Nothing in the exported HTML executes, but html-to-image (running in the
 * parent) can serialize it because it's same-origin.
 */
async function snapshotScreen(html: string): Promise<string> {
  const iframe = document.createElement('iframe');
  iframe.sandbox.add('allow-same-origin');
  iframe.style.position = 'fixed';
  iframe.style.left = '-9999px';
  iframe.style.width = '1280px';
  iframe.style.height = '800px';
  document.body.appendChild(iframe);

  await new Promise<void>((resolve) => {
    iframe.onload = () => resolve();
    iframe.srcdoc = `<!doctype html><html><head><script src="https://cdn.tailwindcss.com"><\/script></head><body>${html}</body></html>`;
  });

  // Give Tailwind's CDN JIT a beat to inject its stylesheet before capture.
  await new Promise((r) => setTimeout(r, 400));

  const body = iframe.contentDocument?.body;
  const dataUrl = body ? await toPng(body, { pixelRatio: 2 }) : '';
  document.body.removeChild(iframe);
  return dataUrl;
}

function styleGuideMarkdown(project: Project): string {
  const c = project.color_theme;
  const colorLines = c
    ? Object.entries(c)
        .map(([k, v]) => `- **${k}**: \`${v}\``)
        .join('\n')
    : '_No tokens saved._';

  return `# ${project.name} — Style Guide

## Colors
${colorLines}

## Typography
Font pairing: ${project.font_pairing ?? '\u2014'}

## Spacing scale
4px, 8px, 12px, 16px, 24px, 32px, 48px, 64px

Generated by ufo.
`;
}

export async function exportProjectZip(project: Project, screens: Screen[]) {
  const zip = new JSZip();

  zip.file('style-guide.md', styleGuideMarkdown(project));

  for (const screen of screens) {
    zip.file(`${screen.name}.html`, screen.code);
    try {
      const png = await snapshotScreen(screen.code);
      if (png) {
        const base64 = png.split(',')[1];
        zip.file(`${screen.name}.png`, base64, { base64: true });
      }
    } catch (err) {
      console.error(`Snapshot failed for ${screen.name}`, err);
      // Missing PNG shouldn't block the rest of the export.
    }
  }

  const blob = await zip.generateAsync({ type: 'blob' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${project.name.replace(/\s+/g, '-').toLowerCase()}.zip`;
  a.click();
  URL.revokeObjectURL(url);
}
